name: Manual Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: BMTE-linux-64bit
            separator: ":"
          - os: windows-latest
            asset_name: BMTE-windows-64bit
            separator: ";"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build with PyInstaller (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller main.py `
            --noconsole `
            --name BMTE `
            --add-data "Data${{ matrix.separator }}Data"

      - name: Build with PyInstaller (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pyinstaller main.py \
            --noconsole \
            --name BMTE \
            --add-data "Data${{ matrix.separator }}Data"

      - name: Create ZIP archive (Windows)
        if: matrix.os == 'windows-latest'
        working-directory: dist
        run: |
          Compress-Archive -Path ./BMTE -DestinationPath ../${{ matrix.asset_name }}-${{ github.event.inputs.version }}.zip

      - name: Create ZIP archive (Linux)
        if: matrix.os == 'ubuntu-latest'
        working-directory: dist
        run: |
          zip -r ../${{ matrix.asset_name }}-${{ github.event.inputs.version }}.zip ./BMTE

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}-${{ github.event.inputs.version }}
          path: ./${{ matrix.asset_name }}-${{ github.event.inputs.version }}.zip
          retention-days: 30
